FROM ruby:3.1.2-bullseye

WORKDIR /app
RUN gem install bundler:2.4.10
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
RUN ["rails", "db:create", "db:migrate", "db:seed"]

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]

