FROM ruby:3.1.2-bullseye

WORKDIR /app
RUN gem install bundler:2.4.10
COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt update -qq && apt install -y yarn
COPY package.json .
COPY yarn.lock .
RUN yarn install

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]

